name: Windows Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          # flutter-version: 'latest' # Optional, defaults to latest stable

      - name: Install dependencies
        run: flutter pub get

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Build Windows
        run: flutter build windows --release

      - name: Create Build Archive
        shell: pwsh
        run: |
          Compress-Archive -Path build\windows\runner\Release\* -DestinationPath inverory_app_windows.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: inverory_app_windows.zip
